export interface User {
    id: string;
    name: string;
    username: string;
    email: string;
    avatarInitial: string;
    bio: string;
    website: string;
    joinedDate: string;
    hasSeenOnboarding: boolean;
}

export const currentUser: User = {
    id: "u_123",
    name: "Alex Creator",
    username: "alexcreator",
    email: "alex@example.com",
    avatarInitial: "A",
    bio: "Creating tools and resources for designers and developers.",
    website: "https://alexcreator.com",
    joinedDate: "2024-01-15T00:00:00Z",
    hasSeenOnboarding: false
};

export const mockLinks = [
    {
        id: "link_01",
        slug: "combo-notion-setup",
        title: "Notion Productivity Setup Guide",
        description: "Follow these steps to set up your Notion workspace and use the attached template to get started instantly.",
        contentMode: "file",
        textContent: "",
        links: [],
        fileAttachments: [ { fileName: "notion-template.zip", fileSize: "1.2 MB", fileType: "zip" } ],
        fileType: "ZIP",
        fileName: "notion-template.zip",
        fileSize: "1.2 MB",
        unlockType: "custom_sponsor",
        adSource: "custom",
        requiresClick: true,
        brandName: "Notion",
        ctaText: "Get Notion Free",
        redirectUrl: "https://notion.so",
        skipAfter: 5,
        customAd: {
            fileName: "notion-promo.mp4",
            fileSize: 10240000,
            fileMimeType: "video/mp4",
            previewUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
            redirectUrl: "https://notion.so",
            requiresClick: true,
            ctaText: "Get Notion Free",
            brandName: "Notion",
            skipAfter: 5,
            impressions: 1200,
            videoWatches: 950,
            clicks: 800
        },
        videoWatches: 950,
        clicks: 800,
        donateEnabled: false,
        isActive: true,
        viewCount: 1200,
        unlockCount: 950,
        conversionRate: "79.1%",
        createdAt: "2024-05-11T12:00:00Z",
        geography: [],
        deviceSplit: { mobile: 50, desktop: 50, tablet: 0 },
    },
    {
        id: "link_02",
        slug: "design-system-pro",
        title: "Pro Design System UI Kit",
        description: "A complete professional design system for Figma with 1000+ components.",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "ZIP",
        fileName: "DesignSystemPro.zip",
        fileSize: "24.5 MB",
        unlockType: "custom_sponsor",
        adSource: "custom",
        requiresClick: false,
        brandName: "Canva",
        ctaText: "Learn More",
        redirectUrl: null,
        skipAfter: 5,
        customAd: {
            fileName: "canva-promo.mp4",
            fileSize: 4500000,
            fileMimeType: "video/mp4",
            previewUrl: "",
            redirectUrl: null,
            requiresClick: false,
            ctaText: "Learn More",
            brandName: "Canva",
            skipAfter: 5,
            impressions: 1420,
            videoWatches: 840,
            clicks: 0
        },
        videoWatches: 840,
        clicks: 0,
        donateEnabled: true,
        isActive: true,
        viewCount: 1420,
        unlockCount: 840,
        conversionRate: "59.1%",
        createdAt: "2024-02-10T10:00:00Z",
        geography: [{ country: "US", percent: 45 }, { country: "UK", percent: 20 }, { country: "IN", percent: 15 }],
        deviceSplit: { mobile: 65, desktop: 30, tablet: 5 },
    },
    {
        id: "link_03",
        slug: "midjourney-prompts",
        title: "100+ Midjourney Prompts for Character Design",
        description: "My personal collection of prompts for generating consistent and detailed characters.",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "PDF",
        fileName: "Midjourney_Characters.pdf",
        fileSize: "4.2 MB",
        unlockType: "custom_sponsor",
        adSource: "custom",
        requiresClick: true,
        brandName: "Grammarly",
        ctaText: "Try Grammarly",
        redirectUrl: "https://grammarly.com",
        skipAfter: 5,
        customAd: {
            fileName: "grammarly-promo.mp4",
            fileSize: 10240000,
            fileMimeType: "video/mp4",
            previewUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
            redirectUrl: "https://grammarly.com",
            requiresClick: true,
            ctaText: "Try Grammarly",
            brandName: "Grammarly",
            skipAfter: 5,
            impressions: 890,
            videoWatches: 650,
            clicks: 612
        },
        videoWatches: 650,
        clicks: 612,
        donateEnabled: false,
        isActive: true,
        viewCount: 890,
        unlockCount: 612,
        conversionRate: "68.7%",
        createdAt: "2024-03-01T14:30:00Z",
        geography: [{ country: "US", percent: 50 }, { country: "CA", percent: 15 }, { country: "AU", percent: 10 }],
        deviceSplit: { mobile: 80, desktop: 15, tablet: 5 },
    },
    {
        id: "link_04",
        slug: "marketing-template",
        title: "Marketing Campaign Template",
        description: "The spreadsheet I use to plan all my successful campaigns.",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "ZIP",
        fileName: "marketing-starter.zip",
        fileSize: "1.8 MB",
        unlockType: "custom_sponsor",
        adSource: "custom",
        requiresClick: false,
        brandName: "Buffer",
        ctaText: "Learn More",
        redirectUrl: null,
        skipAfter: 5,
        customAd: {
            fileName: "buffer-demo.mp4",
            fileSize: 4500000,
            fileMimeType: "video/mp4",
            previewUrl: "",
            redirectUrl: null,
            requiresClick: false,
            ctaText: "Learn More",
            brandName: "Buffer",
            skipAfter: 5,
            impressions: 450,
            videoWatches: 180,
            clicks: 0
        },
        videoWatches: 180,
        clicks: 0,
        donateEnabled: true,
        isActive: true,
        viewCount: 450,
        unlockCount: 180,
        conversionRate: "40.0%",
        createdAt: "2024-04-05T16:45:00Z",
        geography: [{ country: "IN", percent: 40 }, { country: "US", percent: 30 }, { country: "DE", percent: 10 }],
        deviceSplit: { mobile: 20, desktop: 78, tablet: 2 },
    },
    {
        id: "link_05",
        slug: "illustration-pack",
        title: "3D Illustration Vector Pack",
        description: "A huge pack of 3D illustrations for your UI designs.",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "ZIP",
        fileName: "3d_vectors.zip",
        fileSize: "50 MB",
        unlockType: "custom_sponsor",
        adSource: "custom",
        requiresClick: false,
        brandName: "Adobe",
        ctaText: "Learn More",
        redirectUrl: null,
        skipAfter: 6,
        customAd: {
            fileName: "adobe-demo.mp4",
            fileSize: 6500000,
            fileMimeType: "video/mp4",
            previewUrl: "",
            redirectUrl: null,
            requiresClick: false,
            ctaText: "Learn More",
            brandName: "Adobe",
            skipAfter: 6,
            impressions: 350,
            videoWatches: 210,
            clicks: 0
        },
        videoWatches: 210,
        clicks: 0,
        donateEnabled: true,
        isActive: true,
        viewCount: 350,
        unlockCount: 210,
        conversionRate: "60.0%",
        createdAt: "2024-04-10T16:45:00Z",
        geography: [],
        deviceSplit: { mobile: 20, desktop: 78, tablet: 2 },
    },
    {
        id: "link_06",
        slug: "youtube-thumbnail-pack",
        title: "Viral YouTube Thumbnail PSDs",
        description: "5 fully editable Photoshop templates for high-CTR thumbnails.",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "ZIP",
        fileName: "YT_Thumbnails.zip",
        fileSize: "45.2 MB",
        unlockType: "custom_sponsor",
        adSource: "custom",
        requiresClick: true,
        brandName: "Figma",
        ctaText: "Download Figma",
        redirectUrl: "https://figma.com",
        skipAfter: 5,
        customAd: {
            fileName: "figma-app.mp4",
            fileSize: 8500000,
            fileMimeType: "video/mp4",
            previewUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800",
            redirectUrl: "https://figma.com",
            requiresClick: true,
            ctaText: "Download Figma",
            brandName: "Figma",
            skipAfter: 5,
            impressions: 110,
            videoWatches: 85,
            clicks: 70
        },
        videoWatches: 85,
        clicks: 70,
        donateEnabled: false,
        isActive: true,
        viewCount: 110,
        unlockCount: 70,
        conversionRate: "63.6%",
        createdAt: "2024-04-18T08:00:00Z",
        geography: [],
        deviceSplit: { mobile: 0, desktop: 0, tablet: 0 },
    },
    {
        id: "link_email_001",
        slug: "design-system-checklist",
        title: "Design System Setup Checklist",
        description: "A 47-point checklist for setting up a scalable design system from scratch.",
        unlockType: "email_subscribe",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "pdf",
        fileName: "design-system-checklist.pdf",
        fileSize: "1.2 MB",
        fileAttachments: [{ fileName: "design-system-checklist.pdf", fileSize: "1.2 MB", fileType: "pdf", fileEmoji: "📄" }],
        donateEnabled: true,
        isActive: true,
        viewCount: 2840,
        unlockCount: 1203,
        views: 2840,
        unlocks: 1203,
        createdAt: "2024-05-12T12:00:00Z",
        conversionRate: "42.4%",
        geography: [],
        deviceSplit: { mobile: 50, desktop: 50, tablet: 0 },
        emailConfig: {
            newsletterName: "Design Systems Weekly",
            newsletterDescription: "Weekly insights on design systems, component libraries, and scalable UI.",
            incentiveText: "Subscribe to access this checklist and join 3,200 designers getting weekly systems thinking.",
            platform: "convertkit",
            platformDisplayName: "ConvertKit",
            archiveUrl: null,
            confirmationMessage: "Check your inbox to confirm! Your checklist unlocks immediately.",
            totalSubscribers: 1203,
            thisMonthSubscribers: 187,
        }
    },
    {
        id: "link_email_002",
        slug: "freelance-email-scripts",
        title: "7 Freelance Email Scripts That Get Replies",
        description: "Copy-paste email scripts for cold outreach, rate increases, late payments, and scope creep.",
        unlockType: "email_subscribe",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "pdf",
        fileName: "freelance-email-scripts.pdf",
        fileSize: "890 KB",
        fileAttachments: [{ fileName: "freelance-email-scripts.pdf", fileSize: "890 KB", fileType: "pdf", fileEmoji: "📄" }],
        donateEnabled: false,
        isActive: true,
        viewCount: 1560,
        unlockCount: 743,
        views: 1560,
        unlocks: 743,
        createdAt: "2024-05-13T12:00:00Z",
        conversionRate: "47.6%",
        geography: [],
        deviceSplit: { mobile: 50, desktop: 50, tablet: 0 },
        emailConfig: {
            newsletterName: "Freelance Forward",
            newsletterDescription: "Practical freelance business advice every two weeks. No fluff.",
            incentiveText: "Subscribe and get the scripts plus a new freelance template every two weeks.",
            platform: "beehiiv",
            platformDisplayName: "Beehiiv",
            archiveUrl: "https://freelanceforward.beehiiv.com",
            confirmationMessage: "You're subscribed! Your scripts are ready below.",
            totalSubscribers: 743,
            thisMonthSubscribers: 98,
        }
    },
    {
        id: "link_social_001",
        slug: "figma-shortcuts-sheet",
        title: "Ultimate Figma Shortcuts Cheat Sheet",
        description: "Every Figma keyboard shortcut organized by workflow. Print-ready PDF.",
        unlockType: "social_follow",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "pdf",
        fileName: "figma-shortcuts.pdf",
        fileSize: "2.1 MB",
        fileAttachments: [{ fileName: "figma-shortcuts.pdf", fileSize: "2.1 MB", fileType: "pdf", fileEmoji: "📄" }],
        donateEnabled: false,
        isActive: true,
        viewCount: 4210,
        unlockCount: 2890,
        views: 4210,
        unlocks: 2890,
        createdAt: "2024-05-14T12:00:00Z",
        conversionRate: "68.6%",
        geography: [],
        deviceSplit: { mobile: 50, desktop: 50, tablet: 0 },
        socialConfig: {
            followTargets: [
                {
                    id: "target_s1_001",
                    type: "platform",
                    platform: "instagram",
                    handle: "@uidesigns",
                    profileUrl: "https://instagram.com/uidesigns",
                    customLabel: null, customUrl: null, customIcon: null,
                    instructionText: null,
                },
                {
                    id: "target_s1_002",
                    type: "platform",
                    platform: "tiktok",
                    handle: "@uidesigns",
                    profileUrl: "https://tiktok.com/@uidesigns",
                    customLabel: null, customUrl: null, customIcon: null,
                    instructionText: null,
                }
            ],
            customHeading: "Follow for daily Figma tips and free resources",
            followDescription: "I post daily Figma tutorials, UI breakdowns, and free resource drops. Come join.",
            totalFollows: 2890,
            thisMonthFollows: 340,
        }
    },
    {
        id: "link_social_002",
        slug: "python-beginners-guide",
        title: "Python for Complete Beginners — 30 Day Plan",
        description: "A structured 30-day learning plan with daily exercises, resources, and project ideas.",
        unlockType: "social_follow",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "pdf",
        fileName: "python-30day-plan.pdf",
        fileSize: "3.4 MB",
        fileAttachments: [{ fileName: "python-30day-plan.pdf", fileSize: "3.4 MB", fileType: "pdf", fileEmoji: "📄" }],
        donateEnabled: true,
        isActive: true,
        viewCount: 3180,
        unlockCount: 1940,
        views: 3180,
        unlocks: 1940,
        createdAt: "2024-05-15T12:00:00Z",
        conversionRate: "61.0%",
        geography: [],
        deviceSplit: { mobile: 50, desktop: 50, tablet: 0 },
        socialConfig: {
            followTargets: [
                {
                    id: "target_s2_001",
                    type: "platform",
                    platform: "youtube",
                    handle: "@devhints",
                    profileUrl: "https://youtube.com/@devhints",
                    customLabel: null, customUrl: null, customIcon: null,
                    instructionText: "Subscribe to the channel",
                },
                {
                    id: "target_s2_002",
                    type: "platform",
                    platform: "twitter",
                    handle: "@devhints",
                    profileUrl: "https://twitter.com/devhints",
                    customLabel: null, customUrl: null, customIcon: null,
                    instructionText: null,
                },
                {
                    id: "target_s2_003",
                    type: "custom",
                    platform: null,
                    handle: null,
                    profileUrl: null,
                    customLabel: "Join our Discord server",
                    customUrl: "https://discord.gg/devhints",
                    customIcon: "💬",
                    instructionText: "Join the community",
                }
            ],
            customHeading: "Subscribe for weekly Python tutorials and coding challenges",
            followDescription: "Free weekly Python tutorials, project walkthroughs, and coding challenges for beginners.",
            totalFollows: 1940,
            thisMonthFollows: 234,
        }
    },
    {
        id: "link_accountability_001",
        slug: "morning-routine-accountability",
        title: "14-Day Morning Routine Challenge",
        description: "Pair up with someone building a morning routine. Check in daily. Support each other.",
        unlockType: "accountability",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "",
        fileName: "",
        fileSize: "",
        fileAttachments: [],
        donateEnabled: false,
        isActive: true,
        viewCount: 1840,
        unlockCount: 0,
        views: 1840,
        unlocks: 0,
        createdAt: "2024-05-16T12:00:00Z",
        conversionRate: "0.0%",
        geography: [],
        deviceSplit: { mobile: 50, desktop: 50, tablet: 0 },
        accountabilityConfig: {
            topic: "Building a consistent morning routine",
            description: "Pair up with a stranger who is also trying to build a morning routine. You will check in with each other every day for 14 days. That is it. No app to download. No community to join. Just you, one other person, and a daily check-in.",
            commitmentPrompt: "What specific morning habit will you commit to practicing every day for 14 days?",
            durationDays: 14,
            checkInFrequency: "daily",
            guidelines: "Be honest with your partner. Check in every day. If you miss a day, say so. No judgment.",
            creatorResourceUrl: "https://example.com/morning-guide",
            creatorResourceLabel: "Read the creator's morning routine guide",
            waitingRoomEnabled: true,
            maxParticipants: null,
            totalParticipants: 234,
            activePairs: 47,
            completedPairs: 156,
            isAcceptingParticipants: true,
        }
    },
    {
        id: "link_accountability_002",
        slug: "freelance-goal-accountability",
        title: "30-Day Freelance Revenue Goal",
        description: "Set a freelance revenue goal for next month and get an accountability partner to keep you on track.",
        unlockType: "accountability",
        contentMode: "file",
        textContent: "",
        links: [],
        fileType: "",
        fileName: "",
        fileSize: "",
        fileAttachments: [],
        donateEnabled: false,
        isActive: true,
        viewCount: 980,
        unlockCount: 0,
        views: 980,
        unlocks: 0,
        createdAt: "2024-05-17T12:00:00Z",
        conversionRate: "0.0%",
        geography: [],
        deviceSplit: { mobile: 50, desktop: 50, tablet: 0 },
        accountabilityConfig: {
            topic: "Hitting your freelance revenue goal",
            description: "You set a freelance income goal. We pair you with another freelancer with a similar goal. You check in twice a week for 30 days. Most people who do this hit their goal or come close.",
            commitmentPrompt: "What is your freelance revenue goal for the next 30 days, and what is one specific action you will take this week to move toward it?",
            durationDays: 30,
            checkInFrequency: "every_other_day",
            guidelines: "Share your numbers honestly. Celebrate each other's wins. Call each other out on excuses.",
            creatorResourceUrl: null,
            creatorResourceLabel: null,
            waitingRoomEnabled: true,
            maxParticipants: 100,
            totalParticipants: 89,
            activePairs: 23,
            completedPairs: 31,
            isAcceptingParticipants: true,
        }
    }
];

export const mockAccountabilityParticipants = [
    {
        id: "participant_current",
        linkId: "link_accountability_001",
        email: "currentuser@email.com",
        displayName: "You",
        commitmentStatement: "Wake up at 6am and journal for 10 minutes before opening my phone.",
        pairId: "participant_pair",
        isPaired: true,
        pairedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        sessionToken: "mock-session-token-001",
        expiresAt: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
        status: "active",
        joinedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "participant_pair",
        linkId: "link_accountability_001",
        email: "partner@email.com",
        displayName: "Jordan",
        commitmentStatement: "No phone for first 30 minutes after waking. Cold shower every morning.",
        pairId: "participant_current",
        isPaired: true,
        pairedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        sessionToken: "mock-session-token-002",
        expiresAt: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
        status: "active",
        joinedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    }
];

export const mockChatMessages = [
    {
        id: "msg_001",
        pairSessionId: "participant_current_participant_pair",
        senderId: "participant_pair",
        senderName: "Jordan",
        senderInitial: "J",
        content: "Hey! Just joined. Super excited about this. What's your morning routine goal?",
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        isRead: true,
    },
    {
        id: "msg_002",
        pairSessionId: "participant_current_participant_pair",
        senderId: "participant_current",
        senderName: "You",
        senderInitial: "Y",
        content: "Morning! I'm trying to journal every day before I check my phone. Day 2 done ✓",
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        isRead: true,
    },
    {
        id: "msg_003",
        pairSessionId: "participant_current_participant_pair",
        senderId: "participant_pair",
        senderName: "Jordan",
        senderInitial: "J",
        content: "That's great! I did my cold shower this morning. Brutal but worth it 😅",
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
        isRead: true,
    },
    {
        id: "msg_004",
        pairSessionId: "participant_current_participant_pair",
        senderId: "participant_pair",
        senderName: "Jordan",
        senderInitial: "J",
        content: "Day 3 check-in — did you journal this morning?",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        isRead: false,
    },
];

export const mockAutoResponses = [
    "Day check-in! How are you doing today?",
    "Keep it up! Consistency is everything.",
    "I almost skipped today but remembered we were checking in 😅",
    "How are you finding it so far?",
    "Day [n] done! Feeling good about this.",
    "Any tips from your experience so far?",
    "We're halfway through! Can't believe it.",
    "Almost there! Last few days — let's finish strong.",
];

export const mockActivity = [
    { id: "act_1", type: "unlock", description: "⭐ Sponsor video watched on Noton Productivity Setup Guide", timestamp: "2 mins ago", resourceTitle: "" },
    { id: "act_2", type: "unlock", description: "🖱️ Sponsor link clicked on Pro Design System UI Kit", timestamp: "15 mins ago", resourceTitle: "" },
    { id: "act_5", type: "unlock", description: "⭐ Sponsor video watched on Illustration Pack", timestamp: "5 hours ago", resourceTitle: "" },
    { id: "act_7", type: "unlock", description: "🖱️ Sponsor link clicked on Midjourney Prompts", timestamp: "Yesterday", resourceTitle: "" },
    { id: "act_8", type: "creation", description: "Created new link Viral YouTube Thumbnail PSDs", timestamp: "3 days ago", resourceTitle: "" },
    { id: "act_9", type: "unlock", description: "⭐ Sponsor video watched on Pro Design System UI Kit", timestamp: "3 days ago", resourceTitle: "" },
    { id: "act_10", type: "unlock", description: "⭐ Sponsor video watched on Marketing Campaign Template", timestamp: "4 days ago", resourceTitle: "" },
];





export const mockCreatorProfile = { ...currentUser, links: mockLinks.filter(l => l.isActive) };

import type { EmailConfigData } from '../components/dashboard/EmailConfigForm';
import type { SocialConfigData } from '../components/dashboard/SocialConfigForm';
import type { AccountabilityConfigData } from '../components/dashboard/AccountabilityConfigForm';

export interface ExploreResource {
    id: string;
    slug: string;
    title: string;
    creatorName: string;
    creatorHandle: string;
    creatorAvatar: string;
    verified: boolean;
    fileType: string;
    unlockCount: string;
    category: string;
    adSource?: string;
    isCustomSponsor?: boolean;
    sponsorName?: string;
    requiresClick?: boolean;
    isActive?: boolean;
    customAd?: {
        fileName: string;
        fileSize: number;
        fileMimeType: string;
        previewUrl: string;
        redirectUrl: string | null;
        requiresClick: boolean;
        ctaText: string;
        brandName: string;
        skipAfter: number;
        impressions: number;
        videoWatches: number;
        clicks: number;
    };
    description?: string;
    fileSize?: string;
    donateEnabled?: boolean;
    contentMode?: "file";
    unlockType?: "custom_sponsor" | "email_subscribe" | "social_follow" | "accountability";
    emailConfig?: EmailConfigData;
    socialConfig?: SocialConfigData;
    accountabilityConfig?: AccountabilityConfigData;
}

export const mockExploreResources: ExploreResource[] = [
    {
        id: "exp_1",
        slug: "design-system-pro",
        title: "Pro Design System UI Kit",
        creatorName: "Alex Creator",
        creatorHandle: "alexcreator",
        creatorAvatar: "A",
        verified: true,
        fileType: "ZIP",
        unlockCount: "1.2K",
        category: "Templates",
        adSource: "custom",
        requiresClick: true,
        sponsorName: "Figma"
    },
    {
        id: "exp_2",
        slug: "ai-prompt-pack",
        title: "500+ ChatGPT Prompts for Marketing",
        creatorName: "Sarah M.",
        creatorHandle: "sarahmarket",
        creatorAvatar: "S",
        verified: false,
        fileType: "PDF",
        unlockCount: "840",
        category: "Prompts",
        adSource: "custom",
        requiresClick: false,
        sponsorName: "Grammarly",
        unlockType: "email_subscribe",
        emailConfig: {
            newsletterName: "Sarah's Marketing Newsletter",
            newsletterDescription: "Get weekly marketing prompts and insights delivered to your inbox.",
            incentiveText: "Subscribe to unlock these 500 prompts and step up your marketing game.",
            platform: "direct",
            platformDisplayName: "Direct",
            archiveUrl: null,
            confirmationMessage: "Check your inbox to confirm!"
        }
    },
    {
        id: "exp_3",
        slug: "freelance-notion",
        title: "Freelance OS Notion Template",
        creatorName: "Dev Dave",
        creatorHandle: "devdave",
        creatorAvatar: "D",
        verified: true,
        fileType: "ZIP",
        unlockCount: "2.1K",
        category: "Templates",
        adSource: "custom",
        requiresClick: true,
        sponsorName: "Notion"
    },
    {
        id: "exp_4",
        slug: "luts-pack",
        title: "Cinematic Video LUTs Pack",
        creatorName: "Video Creator",
        creatorHandle: "vidcreator",
        creatorAvatar: "V",
        verified: false,
        fileType: "ZIP",
        unlockCount: "350",
        category: "Videos",
        adSource: "custom",
        requiresClick: false,
        sponsorName: "Adobe",
        unlockType: "social_follow",
        socialConfig: {
            followTargets: [
                {
                    id: "target_exp_4_001",
                    type: "platform",
                    platform: "twitter",
                    handle: "vidcreator",
                    profileUrl: "https://twitter.com/vidcreator",
                    customLabel: null, customUrl: null, customIcon: null,
                    instructionText: null,
                }
            ],
            customHeading: "Follow me for daily video editing tips",
            followDescription: "Get the latest insights, free LUTs, and more."
        }
    },
    {
        id: "exp_5",
        slug: "resume-template",
        title: "Modern Minimalist Resume Template",
        creatorName: "Career Coach",
        creatorHandle: "careercoach",
        creatorAvatar: "C",
        verified: false,
        fileType: "DOC",
        unlockCount: "5.4K",
        category: "Guides",
        adSource: "custom",
        requiresClick: true,
        sponsorName: "Canva"
    },
    {
        id: "exp_6",
        slug: "procreate-brushes",
        title: "Watercolor Procreate Brushes",
        creatorName: "Artist Anna",
        creatorHandle: "annaart",
        creatorAvatar: "A",
        verified: true,
        fileType: "ZIP",
        unlockCount: "920",
        category: "Tools",
        adSource: "custom",
        requiresClick: false,
        sponsorName: "Figma",
        unlockType: "accountability",
        accountabilityConfig: {
            topic: "30-Day Drawing Challenge",
            description: "Pair up with another artist to build a daily drawing habit. Share your sketches and stay accountable.",
            commitmentPrompt: "What are you committing to draw every day?",
            durationDays: 30,
            checkInFrequency: "daily",
            guidelines: "Be supportive, share your work honestly.",
            creatorResourceUrl: null,
            creatorResourceLabel: null,
            waitingRoomEnabled: true,
            maxParticipants: 100
        }
    },
    {
        id: "exp_7",
        slug: "startup-pitch",
        title: "Startup Pitch Deck Template",
        creatorName: "Founder Joe",
        creatorHandle: "founderjoe",
        creatorAvatar: "F",
        verified: false,
        fileType: "PDF",
        unlockCount: "135",
        category: "Templates",
        adSource: "custom",
        requiresClick: true,
        sponsorName: "Buffer"
    },
    {
        id: "exp_8",
        slug: "code-snippets",
        title: "100 Useful JS Code Snippets",
        creatorName: "JS Ninja",
        creatorHandle: "jsninja",
        creatorAvatar: "J",
        verified: true,
        fileType: "PDF",
        unlockCount: "3.2K",
        category: "Guides",
        adSource: "custom",
        requiresClick: false,
        sponsorName: "Grammarly"
    }
];





