import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ChevronRight } from 'lucide-react';
import { getAvatarColor } from '../lib/utils';

const FILTERS = [
    { id: 'all', label: 'All', color: '#111' },
    { id: 'sponsor', label: '⭐ Custom Sponsor', color: '#6366F1' },
    { id: 'email', label: '📧 Email Subscribe', color: '#166534' },
    { id: 'social', label: '👥 Social Follow', color: '#2563EB' },
    { id: 'accountability', label: '🤝 Accountability', color: '#B45309' },
    { id: 'premium', label: '🔒 Premium Media', color: '#E8312A' }
];

const CARDS = [
    {
        id: "card-1",
        headerGradient: "linear-gradient(135deg, #6366F1, #8B5CF6)",
        headerEmoji: "⭐", headerTitle: "Brand Partnerships",
        badge: "⭐ Custom Sponsor", badgeColor: "#6366F1",
        creatorType: "Creator with brand deals",
        desc: "You have a direct relationship with a brand — they pay you to reach your audience. Instead of a dedicated post that gets buried in the algorithm, gate your most valuable content behind their video ad. Your audience watches the brand's video to access your resource for free. Your sponsor gets guaranteed impressions from an actively engaged audience. You keep 100% of your deal.",
        uploads: ["📄 Exclusive guide", "📊 Templates", "🎯 Playbooks", "💡 Research"],
        valueLabel: "Real value:",
        valueStmt: "A creator charging $500 for a 30-day sponsored link campaign earns $500. AdGate charges zero commission on deals under $500/month. Every dollar goes directly to you. Your sponsor gets verified impression data and a campaign report generated in one tap.",
        avatar: "P", handle: "productivitylab", ctaText: "Create a Sponsor Link →", ctaColor: "#6366F1", types: ["sponsor"]
    },
    {
        id: "card-2",
        headerGradient: "linear-gradient(135deg, #6366F1, #8B5CF6)",
        headerEmoji: "⭐", headerTitle: "First Sponsor Deal",
        badge: "⭐ Custom Sponsor", badgeColor: "#6366F1",
        creatorType: "Emerging creator · 1K–10K audience",
        desc: "You do not need 100,000 followers to land your first brand deal. Micro-creators with engaged niche audiences consistently outperform large generalist accounts on conversion. Upload your first sponsor's video, set a redirect to their site, and share the link. The sponsor gets a professional campaign report showing impressions, completion rate, and CTA clicks. That report is your proof of concept for the next deal.",
        uploads: ["🎨 Niche resources", "📋 Starter kits", "📖 Guides", "🔧 Tools list"],
        valueLabel: "Real value:",
        valueStmt: "A micro-creator charging $150 for a 14-day campaign earns $150 with zero fee. The sponsor report generated by AdGate makes your pitch to the next sponsor significantly stronger — you are not asking them to trust you, you are showing them a verified previous campaign.",
        avatar: "F", handle: "fashionbasics_", ctaText: "Upload Your First Sponsor →", ctaColor: "#6366F1", types: ["sponsor"]
    },
    {
        id: "card-3",
        headerGradient: "linear-gradient(135deg, #166534, #16A34A)",
        headerEmoji: "📧", headerTitle: "Newsletter Growth",
        badge: "📧 Email Subscribe", badgeColor: "#166534",
        creatorType: "Newsletter creator",
        desc: "You publish a newsletter and you know email is the only audience you truly own. Social platforms change algorithms, reduce reach, and occasionally disappear entirely. Your email list does not. Gate your most valuable free resources behind a newsletter subscription and every piece of content you share builds your list passively. The viewer gets the resource for free. You get a subscriber who specifically wanted what you make.",
        uploads: ["📄 Free guides", "📊 Spreadsheet tools", "✅ Checklists", "📦 Resource packs"],
        valueLabel: "Real value:",
        valueStmt: "With 400 monthly resource accesses at 60% conversion you gain approximately 240 new subscribers per month. A newsletter in a business or design niche earning $2 per subscriber per month in course or product revenue generates $480/month from those subscribers alone. The resource you spent one afternoon creating adds to this number every month it stays live.",
        avatar: "D", handle: "designweekly", ctaText: "Build Your Email List →", ctaColor: "#166534", types: ["email"]
    },
    {
        id: "card-4",
        headerGradient: "linear-gradient(135deg, #166534, #16A34A)",
        headerEmoji: "📧", headerTitle: "Pre-Launch Audience",
        badge: "📧 Email Subscribe", badgeColor: "#166534",
        creatorType: "Course creator / Educator",
        desc: "Your next course is three months away from launch. You need an email list of people who specifically want it — not a general audience, not cold ad traffic. Gate a free mini-lesson or a sample chapter behind a newsletter subscription today. The subscribers you capture over the next three months are your warm launch audience. When you email them a launch offer they already know your teaching style and already wanted more.",
        uploads: ["🎓 Mini-lessons", "📖 Sample chapters", "🎯 Frameworks", "🗒️ Worksheets"],
        valueLabel: "Real value:",
        valueStmt: "A creator who runs email-gated resources for three months before a course launch typically arrives at launch day with 500 to 2,000 pre-qualified subscribers depending on how actively they promote the links. A $97 course converting at 5% to a warm list of 1,000 subscribers generates $4,850 at launch. The email gate is the pre-launch infrastructure.",
        avatar: "U", handle: "uxfoundations", ctaText: "Start Building Your List →", ctaColor: "#166534", types: ["email"]
    },
    {
        id: "card-5",
        headerGradient: "linear-gradient(135deg, #1D4ED8, #2563EB)",
        headerEmoji: "👥", headerTitle: "Grow Your Following",
        badge: "👥 Social Follow", badgeColor: "#2563EB",
        creatorType: "Designer / Creative",
        desc: "You spend hours on a Figma file, an icon set, or a UI kit and share it for free. Without a follow gate it gets downloaded and forgotten — the designer gets the file, closes the tab, and never thinks about you again. With a follow gate every download adds a follower who specifically came for your design work. Your social account grows with a pre-qualified audience that has already demonstrated they want what you make.",
        uploads: ["🎨 Figma files", "📐 UI kits", "🖼️ Icon sets", "✏️ Design systems"],
        valueLabel: "Real value:",
        valueStmt: "With 800 monthly link accesses at 70% follow conversion you gain approximately 560 new followers per month from content you are already creating. These are the highest quality followers possible — they found your specific resource and wanted it enough to follow. Their engagement rate is consistently higher than followers gained through general social growth tactics.",
        avatar: "U", handle: "uidesigns", ctaText: "Set Up a Follow Gate →", ctaColor: "#2563EB", types: ["social"]
    },
    {
        id: "card-6",
        headerGradient: "linear-gradient(135deg, #1D4ED8, #2563EB)",
        headerEmoji: "👥", headerTitle: "Developer Audience",
        badge: "👥 Social Follow", badgeColor: "#2563EB",
        creatorType: "Developer / Technical creator",
        desc: "You built a useful script, a configuration file, a prompt template, or a code snippet that other developers want. Share it through AdGate with a YouTube or Twitter follow gate. Every developer who downloads your tool sees your handle and what content you create. The ones who follow are specifically interested in your technical work. Over time your channel grows with an audience that actively seeks developer tools and tutorials.",
        uploads: ["💾 Scripts", "⚙️ Config files", "📦 CLI tools", "🧩 Prompt templates"],
        valueLabel: "Real value:",
        valueStmt: "Developer audiences on YouTube and Twitter convert technical content to course and tool purchases at higher rates than general audiences. 300 developer followers per month compounding over six months is 1,800 highly targeted followers — a meaningful foundation for selling a technical course, a SaaS tool, or a premium template pack.",
        avatar: "D", handle: "devhints", ctaText: "Gate Your Next Dev Resource →", ctaColor: "#2563EB", types: ["social"]
    },
    {
        id: "card-7",
        headerGradient: "linear-gradient(135deg, #92400E, #B45309)",
        headerEmoji: "🤝", headerTitle: "Accountability Community",
        badge: "🤝 Accountability", badgeColor: "#B45309",
        creatorType: "Fitness / Wellness coach",
        desc: "Your audience's problem is not knowledge — they know what to eat and how to exercise. Their problem is consistency. A 14-day morning routine accountability challenge on AdGate pairs your audience members with each other for daily check-ins. You set the topic, the commitment prompt, the duration, and the guidelines. Your audience does the rest. You build a reputation as someone who helps people actually follow through — which is far more valuable than being another source of information.",
        uploads: [], noFileNote: "📋 No file upload needed for this type",
        valueLabel: "Community value:",
        valueStmt: "A creator running a 14-day challenge with 60 participants forms 30 active pairs. Each pair exchanges at least one message per day for 14 days — that is 420 check-ins happening in your challenge community without you facilitating any of them. Participants who complete the challenge associate the result with your brand. They become your most vocal advocates.",
        avatar: "M", handle: "morningmethod_", ctaText: "Create a Challenge →", ctaColor: "#B45309", types: ["accountability"]
    },
    {
        id: "card-8",
        headerGradient: "linear-gradient(135deg, #92400E, #B45309)",
        headerEmoji: "🤝", headerTitle: "Revenue Accountability",
        badge: "🤝 Accountability", badgeColor: "#B45309",
        creatorType: "Business / Freelance creator",
        desc: "You teach freelancers or early-stage business owners. Your audience knows your frameworks but struggles to execute. A 30-day revenue goal accountability challenge gives your audience the external commitment they need. Each participant sets their revenue goal, writes their weekly action plan, and gets paired with another participant at a similar stage. They check in every two days. You sit back and watch your community become the proof of your teaching.",
        uploads: [], noFileNote: "📋 No file upload needed for this type",
        valueLabel: "Community value:",
        valueStmt: "Accountability partnerships improve goal follow-through by documented margins — participants report higher completion rates when they have a specific named partner than when they work alone. A creator running monthly accountability challenges builds a community reputation that no amount of content production can replicate. Your audience does not just consume your advice — they live it, with each other's help.",
        avatar: "F", handle: "freelanceforward_", ctaText: "Run an Accountability Challenge →", ctaColor: "#B45309", types: ["accountability"]
    },
    {
        id: "card-9",
        headerGradient: "linear-gradient(135deg, #BE185D, #E11D48)",
        headerEmoji: "🔒", headerTitle: "Premium Photos",
        badge: "🔒 Premium Media", badgeColor: "#E8312A",
        creatorType: "Photographer / Visual creator",
        desc: "You shoot behind-the-scenes content, extended photo series, raw files, or exclusive shoots that are genuinely more valuable than your public posts. Stop giving away your best work for free. Lock your premium shoot gallery or your raw file pack behind a newsletter subscription or a follow gate. Your most engaged audience — the ones who specifically seek out your deeper work — complete the action. Everyone else keeps seeing your free public content. Your premium work stops being free and starts building your list.",
        uploads: ["📸 Extended shoots", "🖼️ Raw files", "🎞️ Behind-the-scenes", "📦 Full galleries"],
        valueLabel: "Real value:",
        valueStmt: "A photographer with 5,000 Instagram followers sharing a premium shoot behind an email gate and getting 200 accesses per month at 65% conversion adds 130 newsletter subscribers per month. These are the most engaged segment of your audience — they went looking for your extended work. A product or print shop email to this segment converts at significantly higher rates than a general audience broadcast.",
        avatar: "S", handle: "studioframes_", ctaText: "Lock Your Premium Shoot →", ctaColor: "#E8312A", types: ["premium"]
    },
    {
        id: "card-10",
        headerGradient: "linear-gradient(135deg, #B91C1C, #E8312A)",
        headerEmoji: "🔒", headerTitle: "Premium Video",
        dualBadge: [
            { label: "⭐ Custom Sponsor", color: "#6366F1" },
            { label: "👥 Social Follow", color: "#2563EB" }
        ],
        creatorType: "Video creator / Filmmaker",
        desc: "You produce video content that is genuinely too good to give away on YouTube where it earns you fractions of a cent per view. An extended cut, a director's commentary, a raw interview, an unedited workshop recording, a short film — these have real value to your specific audience. Lock them behind a custom sponsor gate, an email subscription, or a social follow. Your viewers get exclusive access. You get a verified audience of people who wanted specifically this.",
        uploads: ["🎬 Extended cuts", "🎥 Raw footage", "🎞️ Short films", "🎤 Full interviews"],
        valueLabel: "Real value:",
        valueStmt: "A video creator locking an extended cut behind a custom sponsor gate charges their sponsor $300 for guaranteed impressions from their most engaged viewers — the ones willing to actively seek exclusive content. Alternatively a follow gate on a locked short film turns every view into a YouTube subscription from a viewer who specifically sought out your work. These subscribers watch future videos at a much higher rate than algorithmically-acquired subscribers.",
        avatar: "N", handle: "narratefilms", ctaText: "Lock Your Premium Video →", ctaColor: "#E8312A", types: ["sponsor", "social", "premium"]
    }
];

const RECOMMENDATIONS = [
    {
        id: "rec-email", title: "Build my email newsletter list", emoji: "📧", tint: "bg-[#EDFAF3]", border: "#BBF7D0",
        iconContainer: "bg-[#BBF7D0]",
        desc: "Email Subscribe is your best fit. Gate your most valuable free resources and every share builds your list.",
        links: ["card-3", "card-4"]
    },
    {
        id: "rec-social", title: "Grow my social following", emoji: "👥", tint: "bg-[#EFF6FF]", border: "#DBEAFE",
        iconContainer: "bg-[#DBEAFE]",
        desc: "Social Follow gates turn every download into a follower. Best for designers, developers, and creators sharing niche resources.",
        links: ["card-5", "card-6"]
    },
    {
        id: "rec-sponsor", title: "Earn money from brand deals", emoji: "⭐", tint: "bg-[#F5F3FF]", border: "#EDE9FE",
        iconContainer: "bg-[#EDE9FE]",
        desc: "Custom Sponsor lets you deliver your brand deal professionally and keep 100%. Works for any creator size.",
        links: ["card-1", "card-2"]
    },
    {
        id: "rec-acc", title: "Build community and help people take action", emoji: "🤝", tint: "bg-[#FFFBEB]", border: "#FEF3C7",
        iconContainer: "bg-[#FEF3C7]",
        desc: "Accountability Pairing is unique to AdGate. No file needed — your audience pairs up and supports each other. Best for coaches and educators.",
        links: ["card-7", "card-8"]
    }
];

export const UseCases = () => {
    const [activeFilter, setActiveFilter] = useState("all");
    const [activeRec, setActiveRec] = useState<string | null>(null);
    const [highlightedCard, setHighlightedCard] = useState<string | null>(null);

    useEffect(() => {
        document.title = "AdGate Use Cases — Building Real Audiences";
    }, []);

    const scrollToCard = (id: string, activateFilters?: string[]) => {
        if (activateFilters) {
            setActiveFilter("all");
        }
        
        // Let state update before scrolling
        setTimeout(() => {
            const el = document.getElementById(id);
            if (el) {
                const yOffset = -80;
                const y = el.getBoundingClientRect().top + window.pageYOffset + yOffset;
                window.scrollTo({ top: y, behavior: 'smooth' });
                setHighlightedCard(id);
                setTimeout(() => setHighlightedCard(null), 1000);
            }
        }, 50);
    };

    return (
        <div className="w-full min-h-screen bg-[#FAF9F7] font-sans pb-[64px] md:pb-0" style={{ fontFamily: 'Söhne, ui-sans-serif, system-ui, sans-serif' }}>
            
            {/* Hero Section */}
            <div className="w-full bg-white pt-[48px] pb-[32px] flex flex-col items-center px-[24px]">
                <div className="bg-[#FFFBEB] border border-[#FDE68A] text-[#92400E] h-[28px] px-[16px] rounded-[12px] flex items-center justify-center text-[11px] font-[800] tracking-[0.5px] mb-6">
                    ✦ Creator Use Cases
                </div>

                <h1 className="text-[26px] md:text-[36px] font-[900] text-[#111] leading-[1.25] text-center mb-4 max-w-[800px]">
                    How creators use AdGate to build real audiences.
                </h1>

                <p className="text-[15px] font-[600] text-[#666] leading-[1.6] text-center max-w-[480px] mb-8">
                    Four unlock types. Seven creator scenarios. One platform.
                </p>

                <div className="w-full max-w-[600px] flex flex-col md:flex-row items-center justify-between border-t border-[#F0F0F0] md:border-none md:border-t-0 pt-6 md:pt-0">
                    <div className="flex flex-col items-center w-full md:w-auto py-4 md:py-0 border-b border-[#F0F0F0] md:border-none">
                        <span className="text-[22px] font-[900] text-[#111]">4</span>
                        <span className="text-[11px] font-[700] text-[#6B6860] mt-1">Unlock Types</span>
                    </div>
                    <div className="hidden md:block w-[1px] h-[32px] bg-[#F0F0F0]"></div>
                    <div className="flex flex-col items-center w-full md:w-auto py-4 md:py-0 border-b border-[#F0F0F0] md:border-none">
                        <span className="text-[22px] font-[900] text-[#111]">0%</span>
                        <span className="text-[11px] font-[700] text-[#6B6860] mt-1">Commission on Sponsor Deals</span>
                    </div>
                    <div className="hidden md:block w-[1px] h-[32px] bg-[#F0F0F0]"></div>
                    <div className="flex flex-col items-center w-full md:w-auto py-4 md:py-0 border-b border-[#F0F0F0] md:border-none">
                        <span className="text-[22px] font-[900] text-[#111]">100%</span>
                        <span className="text-[11px] font-[700] text-[#6B6860] mt-1">Yours to Keep</span>
                    </div>
                    <div className="hidden md:block w-[1px] h-[32px] bg-[#F0F0F0]"></div>
                    <div className="flex flex-col items-center w-full md:w-auto py-4 md:py-0">
                        <span className="text-[22px] font-[900] text-[#111]">Free</span>
                        <span className="text-[11px] font-[700] text-[#6B6860] mt-1">To Start</span>
                    </div>
                </div>
            </div>

            {/* Filter Pills */}
            <div className="w-full bg-[#FAF9F7] sticky top-[64px] md:top-[64px] z-30 pt-4 pb-[24px] overflow-x-auto overflow-y-hidden border-b border-[#E6E2D9]" style={{ scrollbarWidth: 'none' }}>
                <div className="flex px-[16px] md:px-[32px] pr-[32px] gap-[24px] min-w-max max-w-[800px] mx-auto pb-1">
                    {FILTERS.map(f => {
                        const active = activeFilter === f.id;
                        return (
                            <button
                                key={f.id}
                                onClick={() => setActiveFilter(f.id)}
                                className="h-[36px] rounded-[14px] px-[16px] text-[13px] font-[700] whitespace-nowrap transition-all duration-150 flex-shrink-0 border"
                                style={{
                                    backgroundColor: active ? f.color : '#FFFFFF',
                                    color: active ? '#FFFFFF' : '#666',
                                    borderColor: active ? f.color : '#E8E8E8'
                                }}
                            >
                                {f.label}
                            </button>
                        );
                    })}
                </div>
            </div>

            {/* Cards Grid */}
            <div className="w-full flex justify-center px-[24px] md:px-[32px] py-[32px]">
                <div className="w-full max-w-[800px] grid grid-cols-1 md:grid-cols-2 gap-[16px] md:gap-x-[16px] md:gap-y-[24px] items-start">
                    {CARDS.map(card => {
                        const isMatch = activeFilter === 'all' || card.types.includes(activeFilter);
                        const isHighlight = highlightedCard === card.id;

                        return (
                            <div 
                                key={card.id}
                                id={card.id}
                                className="w-full bg-white rounded-[16px] flex flex-col relative"
                                style={{
                                    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
                                    opacity: isMatch ? 1 : 0.25,
                                    transform: isMatch ? 'scale(1)' : 'scale(0.97)',
                                    pointerEvents: isMatch ? 'auto' : 'none',
                                    transition: 'opacity 200ms ease, transform 200ms ease'
                                }}
                            >
                                <style>{`
                                    @keyframes pulse-ring {
                                        0% { box-shadow: 0 0 0 0 rgba(232,49,42,0.6); }
                                        70% { box-shadow: 0 0 0 10px rgba(232,49,42,0); }
                                        100% { box-shadow: 0 0 0 0 rgba(232,49,42,0); }
                                    }
                                `}</style>

                                {/* Highlighter */}
                                {isHighlight && (
                                    <div className="absolute inset-0 rounded-[16px] pointer-events-none z-10" style={{ animation: 'pulse-ring 0.6s ease-out 2' }}></div>
                                )}
                                
                                <div className="absolute inset-0 border border-[#E6E2D9] rounded-[16px] pointer-events-none"></div>

                                {/* Header Strip */}
                                <div className="w-full h-[48px] rounded-t-[16px] flex items-center justify-center gap-[6px] px-4" style={{ background: card.headerGradient }}>
                                    <span className="text-[20px]">{card.headerEmoji}</span>
                                    <span className="text-[14px] font-[800] text-white truncate">{card.headerTitle}</span>
                                </div>

                                <div className="p-[24px] flex flex-col flex-1 h-full">
                                    {/* Badges & Category */}
                                    <div className="flex flex-row items-center justify-between gap-[8px] mb-4">
                                        {card.badge ? (
                                            <div className="h-[22px] px-2 rounded-full flex items-center text-[10px] font-[800] text-white whitespace-nowrap" style={{ backgroundColor: card.badgeColor }}>
                                                {card.badge}
                                            </div>
                                        ) : (
                                            <div className="flex flex-wrap gap-1">
                                                {card.dualBadge?.map((b, i) => (
                                                    <div key={i} className="h-[22px] px-2 rounded-full flex items-center text-[10px] font-[800] text-white whitespace-nowrap" style={{ backgroundColor: b.color }}>
                                                        {b.label}
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                        <span className="text-[11px] font-[700] text-[#6B6860] shrink-0 text-right">{card.creatorType}</span>
                                    </div>

                                    {/* Desc */}
                                    <p className="text-[14px] font-[600] text-[#444] leading-[1.75] mb-6">
                                        {card.desc}
                                    </p>

                                    {/* Uploads */}
                                    {card.uploads.length > 0 ? (
                                        <div className="mb-6">
                                            <span className="block text-[11px] font-[800] text-[#6B6860] uppercase tracking-[0.5px] mb-3">What to lock:</span>
                                            <div className="flex flex-wrap gap-2">
                                                {card.uploads.map((u, idx) => (
                                                    <div key={idx} className="h-[28px] px-[16px] rounded-[14px] bg-[#F6F6F6] text-[#555] text-[12px] font-[700] flex items-center whitespace-nowrap">
                                                        {u}
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ) : card.noFileNote ? (
                                        <div className="mb-6">
                                            <div className="inline-flex h-[28px] px-3 rounded-[12px] bg-[#E8E8E8] text-[#666] text-[11px] font-[700] items-center">
                                                {card.noFileNote}
                                            </div>
                                        </div>
                                    ) : null}

                                    <div className="grow"></div>

                                    {/* Value section */}
                                    <div className="mt-auto mb-6">
                                        <span className="block text-[11px] font-[800] text-[#6B6860] uppercase mb-2 tracking-[0.5px]">{card.valueLabel}</span>
                                        <div className="bg-[#F6F6F6] rounded-[10px] p-[14px]">
                                            <p className="text-[13px] font-[700] text-[#333] leading-[1.65]">
                                                {card.valueStmt}
                                            </p>
                                        </div>
                                    </div>

                                    {/* Creator Strip at bottom */}
                                    <div className="w-auto -mx-[24px] bg-[#FAFAFA] py-[12px] px-[24px] flex items-center gap-3 mb-6">
                                        <div className="w-[28px] h-[28px] rounded-full flex items-center justify-center text-white text-[12px] font-[800] shrink-0" style={{ backgroundColor: getAvatarColor(card.handle) }}>
                                            {card.avatar}
                                        </div>
                                        <div className="flex flex-col">
                                            <span className="text-[12px] font-[700] text-[#555] leading-[1.1]">@{card.handle}</span>
                                            <span className="text-[10px] font-[400] text-[#AAA49C] italic">Example creator</span>
                                        </div>
                                    </div>

                                    {/* CTA Button */}
                                    <button className="w-full h-[44px] rounded-[12px] text-white font-[800] text-[14px] flex items-center justify-center transition-opacity hover:opacity-90" style={{ backgroundColor: card.ctaColor }}>
                                        {card.ctaText}
                                    </button>
                                </div>
                            </div>
                        )
                    })}
                </div>
            </div>

            {/* Premium Media Callout Strip */}
            <div className="w-full py-[32px] px-[16px] md:px-[32px] flex items-center justify-center pt-[64px] border-t border-[#E6E2D9] mb-[-64px] pb-[96px]" style={{ background: 'linear-gradient(135deg, #FFF0EF 0%, #F5F3FF 100%)' }}>
                <div className="w-full max-w-[800px] flex flex-col items-start">
                    <div className="bg-[#FFF0EF] text-[#E8312A] h-[24px] px-3 rounded-full flex items-center justify-center text-[11px] font-[800] mb-4">
                        🔒 Premium Media
                    </div>
                    <h2 className="text-[20px] font-[900] text-[#111] leading-[1.3] max-w-[320px] mb-3">
                        Your best work deserves more than free.
                    </h2>
                    <p className="text-[14px] font-[600] text-[#555] leading-[1.75] max-w-[480px] mb-6">
                        Photos, videos, raw files, extended cuts, behind-the-scenes content — you create media that your most engaged audience actively seeks. AdGate lets you lock it behind any unlock type you choose. Email subscribe to build your list. Social follow to grow your audience. Custom sponsor to earn from a brand deal on your most valuable content.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4">
                        <button onClick={() => scrollToCard('card-9', ['premium'])} className="px-[24px] h-[36px] rounded-[14px] border-[1.5px] border-[#E8312A] text-[#E8312A] text-[13px] font-[700] hover:bg-[#FFF0EF] transition-colors min-w-[120px] shrink-0">
                            📸 Photography use case →
                        </button>
                        <button onClick={() => scrollToCard('card-10', ['premium'])} className="px-[24px] h-[36px] rounded-[14px] border-[1.5px] border-[#E8312A] text-[#E8312A] text-[13px] font-[700] hover:bg-[#FFF0EF] transition-colors min-w-[120px] shrink-0">
                            🎬 Video use case →
                        </button>
                    </div>
                </div>
            </div>

            {/* How to Choose */}
            <div className="w-full bg-white flex justify-center py-[64px] px-[24px] border-t border-[#E6E2D9]">
                <div className="w-full max-w-[600px] flex flex-col">
                    <h2 className="text-[20px] font-[900] text-[#111] mb-1">Not sure which type fits you?</h2>
                    <p className="text-[14px] font-[600] text-[#888] mb-8">Answer one question.</p>

                    <span className="text-[15px] font-[700] text-[#333] mb-4">What is your primary goal right now?</span>

                    <div className="flex flex-col gap-3">
                        {RECOMMENDATIONS.map(rec => {
                            const isActive = activeRec === rec.id;
                            return (
                                <div key={rec.id} className="flex flex-col">
                                    <button 
                                        onClick={() => setActiveRec(isActive ? null : rec.id)}
                                        className="w-full h-[56px] rounded-[12px] px-[16px] flex items-center transition-colors bg-white hover:bg-[#FAFAFA]"
                                        style={{ border: isActive ? `1.5px solid ${rec.border}` : '1.5px solid #E8E8E8' }}
                                    >
                                        <div className="w-[32px] h-[32px] rounded-[8px] flex justify-center items-center text-[20px] shrink-0 mr-[12px]" style={{ backgroundColor: rec.iconContainer }}>
                                            {rec.emoji}
                                        </div>
                                        <span className="text-[14px] font-[700] text-[#111] flex-1 text-left">{rec.title}</span>
                                        <ChevronRight size={16} color="#BBB" className={`transition-transform ${isActive ? 'rotate-90' : ''}`} />
                                    </button>

                                    {/* Expandable Recommender Card */}
                                    {isActive && (
                                        <div className="mt-3 rounded-[14px] p-[16px] border-[1.5px] overflow-hidden transition-all duration-150" style={{ backgroundColor: rec.tint, borderColor: rec.border }}>
                                            <p className="text-[14px] font-[700] text-[#333] leading-[1.6] mb-4">
                                                {rec.desc}
                                            </p>
                                            <div className="flex flex-col sm:flex-row gap-[12px]">
                                                {rec.links.map((linkId, idx) => {
                                                    const cc = CARDS.find(c => c.id === linkId);
                                                    if (!cc) return null;
                                                    return (
                                                        <button 
                                                            key={idx} 
                                                            onClick={e => { e.stopPropagation(); scrollToCard(linkId, cc.types); }} 
                                                            className="flex-1 bg-white border border-[#E8E8E8] h-[36px] rounded-[8px] flex items-center justify-center text-[12px] font-[700] text-[#111] shadow-sm hover:bg-[#FAFAFA]"
                                                        >
                                                            See {cc.headerTitle}
                                                        </button>
                                                    )
                                                })}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>

            {/* Bottom CTA Strip */}
            <div className="w-full bg-[#111] pt-[48px] pb-[48px] px-[16px] flex flex-col items-center">
                <div className="w-full max-w-[600px] flex flex-col items-center">
                    <h2 className="text-[22px] font-[900] text-white leading-[1.3] text-center mb-2">
                        Start with whichever type fits your goal.
                    </h2>
                    <p className="text-[14px] font-[600] text-[rgba(255,255,255,0.65)] text-center mb-[32px]">
                        Free to start. No subscription. No commission on your first sponsor deal.
                    </p>

                    <div className="w-full sm:w-auto flex flex-col sm:flex-row gap-4 mb-3">
                        <Link to="/" className="w-full sm:w-[220px] h-[52px] rounded-[14px] bg-[#E8312A] text-white flex items-center justify-center text-[15px] font-[900] hover:opacity-90 transition-opacity">
                            Create Your First Link →
                        </Link>
                        <Link to="/how-it-works" className="w-full sm:w-[220px] h-[52px] rounded-[14px] bg-transparent border-[1.5px] border-[rgba(255,255,255,0.3)] text-white flex items-center justify-center text-[15px] font-[900] hover:bg-[rgba(255,255,255,0.1)] transition-colors">
                            See How It Works →
                        </Link>
                    </div>

                    <p className="text-[11px] text-[rgba(255,255,255,0.45)] text-center">
                        🔒 No credit card · Free forever for email and follow gates
                    </p>
                </div>
            </div>
            
            <footer className="w-full bg-white border-t border-[#E6E2D9] py-12 px-[16px] flex flex-col items-center">
                <div className="w-full max-w-[800px] flex flex-col md:flex-row justify-between items-center gap-6">
                    <div className="flex items-center gap-2 opacity-80">
                        <div className="w-[24px] h-[24px] rounded-[8px] bg-[#21201C] text-white flex items-center justify-center font-[900] text-[10px] leading-none shrink-0">
                            AG
                        </div>
                        <span className="font-[900] text-[16px] tracking-tight text-[#21201C]">AdGate</span>
                    </div>

                    <div className="flex items-center gap-6 text-[13px] font-[700] text-[#6B6860]">
                        <Link to="/use-cases" className="hover:text-[#21201C] transition-colors">Use Cases</Link>
                        <Link to="/terms" className="hover:text-[#21201C] transition-colors">Terms of Service</Link>
                        <Link to="/privacy" className="hover:text-[#21201C] transition-colors">Privacy Policy</Link>
                        <Link to="/contact" className="hover:text-[#21201C] transition-colors">Contact</Link>
                    </div>

                    <div className="text-[12px] font-[700] text-[#AAA49C]">
                        © {new Date().getFullYear()} AdGate Inc. All rights reserved.
                    </div>
                </div>
            </footer>
        </div>
    );
};
